### ISSUE TITLE
Handle WebGL context loss

### ISSUE THREAD

**Issue by aduros** [aduros/wasm4#12]
Context loss happens on some devices when coming out of sleep/suspend.

**Comment by takaeri** [comment]
Take a look into [this](https://www.khronos.org/webgl/wiki/HandlingContextLost)

> 1) add a lost context handler and tell it to prevent the default behavior
```js
var canvas = document.getElementById("myCanvas");
canvas.addEventListener("webglcontextlost", function(event) {
    event.preventDefault();
}, false);
```
> 2) re-setup all your WebGL state and re-create all your WebGL resources when the context is restored.
```js
canvas.addEventListener(
    "webglcontextrestored", setupWebGLStateAndResources, false);
```

I can submit a PR but I'm quite busy this week

**Comment by takaeri** [comment]
Once #44 lands, I'll work on handling this issue

**Comment by aduros** [comment]
#44 has landed if you still want to take a crack at this one :smiley:
