### ISSUE TITLE
Add FPS overlay bound to a hotkey

### ISSUE THREAD

**Issue by DenialAdams** [aduros/wasm4#136]
FaberVitale was kind enough to explain how to do this at the browser level in https://github.com/aduros/wasm4/issues/24#issuecomment-955980892, but I was thinking that a simple FPS counter on a hotkey would be nice.

**Comment by joshgoebel** [comment]
Some kind of rough CPU usage metric based on "time to render frame" / 16.66666ms would be nice as well, IMHO.  Really I want to know WHY the frames are being skipped, not just what the FPS is... for a well behaving game wouldn't it always be 60?
