### ISSUE TITLE
Nim support

### ISSUE THREAD

**Issue by aduros** [aduros/wasm4#147]
https://github.com/Yardanico/wasm4nim/

- [x] `w4 new`: Add new project template
- [x] `w4 watch`: Add new filename suffix + build/run support
- [x] `w4 png2src`: Add new language parameter
- [x] Website: Setup documentation
- [ ] Website: Translated code snippets for all guide pages

**Comment by Yardanico** [comment]
Hi! I'd be glad to add Nim to wasm4. Some questions:
- Is it better to make code a bit more idiomatic than having a 1:1 mapping with the WASM-4 itself? For example, defines like `BUTTON_1` or `BUTTON_LEFT` can be made into a Nim enum, but then the names (and usage of functions) will differ. On the other hand, having almost the same interface for all languages can make writing examples much easier, so I'm not sure.

- I assume that wasm4 is a monorepo and so I'll have to commit all changes to the wrapper (although it's so simple that I think it won't have a lot of frequent changes) via the PRs? This is not an issue for me, so I'm just asking out of curiosity :)

**Comment by aduros** [comment]
>     * Is it better to make code a bit more idiomatic than having a 1:1 mapping with the WASM-4 itself? For example, defines like `BUTTON_1` or `BUTTON_LEFT` can be made into a Nim enum, but then the names (and usage of functions) will differ. On the other hand, having almost the same interface for all languages can make writing examples much easier, so I'm not sure.

We could look at it on a case by case basis. How would the usage change if those were enums? If it's just a matter of changing the capitalization and adding a bit of type safety that sounds ok, as long as the function signatures are more or less the same.

>     * I assume that wasm4 is a monorepo and so I'll have to commit all changes to the wrapper (although it's so simple that I think it won't have a lot of frequent changes) via the PRs? This is not an issue for me, so I'm just asking out of curiosity :)

Yup :smiley:

**Comment by tjpalmer** [comment]
@Yardanico Are you still working this?

Also, gingerBill is working on this question of enum naming in Odin. I don't know the current state of the plans, though.

**Comment by aduros** [comment]
@Yardanico Besides the snake tutorial is there any Nim documentation we're missing?

**Comment by Yardanico** [comment]
@aduros No, apart from the snake tutorial all other examples have Nim code as well.

**Comment by aduros** [comment]
Ok, let's consider that a separate issue and close this one :smiley:
