### ISSUE TITLE
Static project name when a new NPM project initialized 

### ISSUE THREAD

**Issue by ttulka** [aduros/wasm4#16]
When running `w4 new --assemblyscript hello-world` the project name is always `cart`.  

I would expect `hello-world` here.

As an enhancement, a wizard with more parameters would be useful (like `npm init`)... :-)

**Comment by aduros** [comment]
Good idea! This should be a perfect first issue if you feel like taking a crack at it :smile: The implementation would be in `cli/lib/new.js`. Probably just need to read the package.json, set the name based on the destDir basename, then save it back out again.

**Comment by aduros** [comment]
That was quick! Thanks :tada: :tada:
