### ISSUE TITLE
Screen output anti-aliased in Safari

### ISSUE THREAD

**Issue by jakeledoux** [aduros/wasm4#170]
It seems that Safari on macOS is applying some form of interpolation to the screen output.

Here's what the default program looks like in Firefox (normal):
<img width="500" alt="Screen Shot 2021-11-22 at 11 20 24 AM" src="https://user-images.githubusercontent.com/5758561/142897814-f221a2ac-b79a-4581-91b9-309ccf57d9d2.png"> 

and here's the same program running in Safari:
<img width="500" alt="Screen Shot 2021-11-22 at 11 20 13 AM" src="https://user-images.githubusercontent.com/5758561/142897889-516cb7d1-cdf5-4ff2-a7f6-33e990dc3307.png">

It's not *that* bad. Honestly at first I just figured that the anti-aliasing was intentional and didn't mind it that much, but it's probably worth looking into at some point in order to make rendering more consistent for everyone.

**Comment by aduros** [comment]
Yes, this is due to a bug in webkit that has been fixed and should be in the next version of Safari: https://bugs.webkit.org/show_bug.cgi?id=193895

**Comment by jakeledoux** [comment]
Figures. It's almost always Safari's fault haha.
