### ISSUE TITLE
Web Runtime doesn't pause when inactive

### ISSUE THREAD

**Issue by christopher-kleine** [aduros/wasm4#172]
When playing on the website, once the game was started, it won't stop even if the canvas loses focus. This is not the case when switching to another tab however.

Steps to reproduce:

1. Open a cart like https://wasm4.org/play/nyancat
2. Click on the Play-Button
3. Switch to another tab
4. Return to the former tab
5. Click somewhere else on the site

Expected result:
- At step 3 the music should stop.
- At step 4 the music should continue.
- At step 5 the music should stop again.

Actual result:
- At step 3 the music stops. (expected)
- At step 4 the music continues. (expected)
- At step 5 the music continues. (not expected)

Side note: Sometimes the sound might actually play a note even when on a different tan.

https://user-images.githubusercontent.com/3718227/142984013-3aab8803-2df0-4d75-990d-1dcfa4460a12.mp4

**Comment by jakeledoux** [comment]
I'll add that I noticed the occasional note playing in the background while writing the nyancat cart, so it's fairly common. I didn't pick up on what caused it though.
