### ISSUE TITLE
Add keyboard controls for Gamepad 2

### ISSUE THREAD

**Issue by aduros** [aduros/wasm4#185]
In order to enable multiplayer games, we should have a way to input for player 2.

Maybe copy Pico's keybinds? Keys ESDF for directionals, QW for action buttons.

Ideally this should work on European keyboard layouts (and maybe even Dvorak).

**Comment by desttinghim** [comment]
I only know US keyboards, but what about WASD and RT? WASD is a pretty common setup for controlling movement, and RT are nearby. I have no idea if it would map well to other layouts. Would it be difficult to make the controls remappable?

**Comment by aduros** [comment]
R is currently mapped to reboot the cart, although we can always change the existing mappings.

One benefit of ESDF is that it works with [French AZERTY keyboards](https://en.wikipedia.org/wiki/AZERTY). I was wrong about QW being used for the buttons in Pico, they actually use LShift or Tab for button 1, and A or Q for button 2.

For now I think we should borrow [Pico's mappings](https://pico-8.fandom.com/wiki/Btn) with ESDF + LShift/Tab + A/Q for Player 2. Also adding N + M keys for Player 1 so that all four hands can comfortably fit on the keyboard :smile:

Making the controls remappable in the future would be nice, but we'll need to design the UI for it.
