### ISSUE TITLE
Handle traps in runtime

### ISSUE THREAD

**Issue by desttinghim** [aduros/wasm4#196]
When a trap instruction happens it indicates that the wasm module has encountered an unrecoverable error. Currently the runtime will keep calling update in a loop when it encounters one, ignoring the error. If there is something broken, this generates a lot of error output. I think we should stop the runtime and possibly display an error to the user (though hopefully the errors will be gone at the point where you are sending it to users).

I think there's a way to get a stack trace too, but I haven't looked into this.

**Comment by aduros** [comment]
Have you checked out the WebAssembly `unreachable` statement?  In C (clang) you can call the `__builtin_trap()` instrinsic to emit this statement. In Zig there's probably something similar.

**Comment by desttinghim** [comment]
Zig has unreachable. The problem is that WASM4 continues running even after this instruction has been reached. It looks like the cause of this is `requestAnimationFrame()` being called before the update function. This means that the next call of the loop is scheduled before the trap instruction stops execution.
