### ISSUE TITLE
wasm-ld memory suggestions

### ISSUE THREAD

**Issue by yowl** [aduros/wasm4#217]
HI,

Are there any suggestions for how to build wasm from LLVM bitcode using wasm-ld,  Specifically for the options:
```
-z stack-size=5242880 --initial-memory=16777216 --max-memory=16777216 --global-base=1024
```
?  There's only 64KB available, so I guess that's the obvious setting for inital-memory and max-memory, but I guess the others are whatever I want (within that limit)?

**Comment by yowl** [comment]
nvm, I see the memory is an import , no memory size args required, just --import-memory.  My c# attempt has some odd blit artifacts, but getting somewhere:
![image](https://user-images.githubusercontent.com/2720041/146827927-a414b4eb-8719-437d-8b5e-c9441384d2ce.png)

**Comment by aduros** [comment]
Interesting!

Here are the linker flags from the [C Makefile](https://github.com/aduros/wasm4/blob/main/cli/assets/templates/c/Makefile): `-zstack-size=1024 --no-entry --import-memory --initial-memory=65536 --max-memory=65536 --global-base=6560`

`--global-base` is important so that the lower memory region is reserved for WASM-4. Otherwise you may get framebuffer corruption like that screenshot.

Definitely let us know how it goes with C#! It would be absolutely game changing to have that supported :grinning:

**Comment by yowl** [comment]
Ah cool, thanks.  yes was just thinking about the framebuffer and where that sits while making some tea.

**Comment by yowl** [comment]
oh, that's awesome, all my problems have gone with CtrlC/V.  Thanks a lot

https://user-images.githubusercontent.com/2720041/146838015-94f53c58-0b32-4e6b-ab66-e84dfbd5f800.mp4

:

**Comment by aduros** [comment]
Nice!!

How is C# coming along? Anything we can help with? It would be awesome to have C# as an option in time for the game jam. If you want to share on Discord this will probably raise a lot of interest :smiley:

**Comment by yowl** [comment]
Yeah, I'm happy to share, but this is not C# as you know it, so don't want to raise expectations.  There's only 64KB of RAM so we have to use what's called "zerosharp" which is C# without the runtime and the GC etc.  Coding C# without the runtime or creating objects is fine for people from a c background, but your typical C# dev is going to find it a bit strange/limiting.  You can do funky stuff with it though.  e.g.

https://github.com/VollRagm/KernelBypassSharp
https://twitter.com/MStrehovsky/status/1213034748848807937
https://medium.com/@scottwaye/c-snake-in-the-browser-c06b56465d63

For complete Wasm4 functionality, what's in the header files needs to be brought across, I've just done these 2 for that mp4
```
        [DllImport("*")]
        static extern void text(byte* data, int x, int y);

        [DllImport("*")]
        static extern void blit(byte* data, int x, int y, uint width, uint height, uint flags);
```
And I need to create a PR to enable the C# compiler (NativeAOT-LLVM) to create a wasm library (no main), but that's pretty small.   Other than that, there's not much to do, a makefile and where to pull bits (NativeAOT-LLVM, llvm (for clang/wasm-ld, the mini runtime- some c and c#) I guess. I'll post in the discord, see what interest there is.
