### ISSUE TITLE
C++ support

### ISSUE THREAD

**Issue by tjpalmer** [aduros/wasm4#221]
This is a strange request. I don't think we need a C++ specific api, but I'd like to add it to the list of language options for a new template. It would generate a main.cpp instead of a main.c, which would then be compiled as C++ rather than C. Maybe could be implemented as custom logic rather than repeating the template in the wasm4 source tree.

I think the only documentation change would be under the "C / C++" Quick Start section, there'd be a "--cpp" option example with a quick explanation.

**Comment by tjpalmer** [comment]
And by "strange" I mean that the support tasks are different than for other languages.

**Comment by joshgoebel** [comment]
> custom logic rather than repeating the template

Why would a template not be sufficient for a getting started project?

> the support tasks are different than for other languages.

The support tasks? Can you elaborate?  Why would it be that different from C?

**Comment by tjpalmer** [comment]
Simple static template is also fine. Just that it would be almost a copy of the C template, so I was just suggesting a custom implementation if folks prefer. Either could be fine.

By different support tasks, I mean there's not really a need for a separate "C++" category for all the documentation, since people would presumably just use the existing C api. So things can stay "C / C++" everywhere, even if there's a `--cpp` for `w4 new`. So the only key needs (I think?) are `w4 new` and a mention of this in the Quick Start section.

**Comment by joshgoebel** [comment]
Nice!
