### ISSUE TITLE
WASM-4 audio too loud

### ISSUE THREAD

**Issue by OliveIsAWord** [aduros/wasm4#233]
WASM-4's audio is significantly louder than is reasonable. Here in the audio graph, you can see clips of a 440 Hz pulse wave tone in each mode. WASM-4 comes in at -6 dB, twice as loud as both Famitracker (an NES music tracker) and FCEUX (a popular NES emulator), both at -12 dB. I would take a guess that we'd find similar results with GameBoy emulators.

![image](https://user-images.githubusercontent.com/89336634/147188832-f7013b88-6d5b-4bc0-b613-91187dbd4220.png)

This is an issue especially for headphone users. Being twice as loud as the maximum volume of other retro systems, to my ears, is nigh on unbearable. I have to wonder if others feel the same way. This is exacerbated by the fact that there is no global volume control anywhere in WASM-4. The only alternative is changing the sustain volume, rendering the attack and decay controls effectively unusable (since they always peak at 100% volume).

To solve, I would recommend scaling the audio amplitude to one half of what it is currently, to bring this fantasy console in line with its retro contemporaries. We could also add a global volume, perhaps a signed byte which maps values [-128, 127] to volumes [0%, 100%].

**Comment by OliveIsAWord** [comment]
merging [this pull request](https://github.com/aduros/wasm4/pull/229) would provide a better alternative than just changing the sustain volume, though it would still be insufficient in actually fixing this issue.

**Comment by rohlem** [comment]
I've also been negatively surprised by the volume every time I open up the examples section (though I thought that was just me).
I'd also be in favour of reducing the average/standard volume, and/or make it configurable in the UI.

**Comment by OliveIsAWord** [comment]
Followup for the triangle and noise graphs.

![image](https://user-images.githubusercontent.com/89336634/147428422-520fc75f-49cf-49f7-a7be-cc8a5f7e3350.png)

WASM-4 produces a signal 4 times greater in amplitude than retro contemporaries, which makes sense with a brief look at [the APU code](https://github.com/aduros/wasm4/blob/main/runtimes/web/src/apu.js#L81). We should reduce these channels to 0.25 amplitude as well to bring it in line.
