### ISSUE TITLE
(zig) Add `tracef` API call  (APIs should have feature parity)

### ISSUE THREAD

**Issue by joshgoebel** [aduros/wasm4#244]
The C API has `tracef`, so should Zig.

**Comment by joshgoebel** [comment]
Not quite the same but this is what I'm using as a stop-gap:

```
pub fn tracef(comptime template: []const u8, args: anytype) void {
    var s : [256]u8 = undefined;
    _ = fmt.bufPrintZ(&s, template, args) catch |err| {
        switch(err) {
            error.NoSpaceLeft =>
                trace("[ERR] tracef buffer not large enough")
        }
        return;
    };
    trace(&s);
}
```

Yes, this is all on the Zig side and using `trace` instead of `tracef` in the runtime.

**Comment by sporksmith** [comment]
Adding the bare extern description seems pretty easy, but it's not very useful without some wrapper code to pack up the arguments.

I threw it into my "snake" toy repo: https://github.com/sporksmith/snake-wasm4/blob/9e56518e63c3a3feac1a30c48ab2d624958fe65b/src/util.zig#L49

Inline for convenience:

```
pub extern fn tracef(x: [*:0]const u8, args: [*]const u8) void;
```

```
fn pack(dst: []u8, val: anytype) []u8 {
    const T = comptime @TypeOf(val);
    const src = @ptrCast(*const [@sizeOf(T)]u8, &val);
    if (dst.len < @sizeOf(T)) {}
    std.mem.copy(u8, dst[0..@sizeOf(T)], src);
    return dst[@sizeOf(T)..];
}

fn charType(c: u8) ?type {
    return switch (c) {
        '%' => null,
        'd', 'c' => i32,
        'x' => u32,
        'f' => f64,
        's' => u32,
        else => unreachable,
    };
}

pub fn tracef(comptime msg: [:0]const u8, args: anytype) void {
    comptime var space_needed = 0;
    {
        comptime var msg_idx = 0;
        inline while (msg_idx < msg.len) : (msg_idx += 1) {
            if (msg[msg_idx] != '%') {
                continue;
            }
            msg_idx += 1;
            const T = charType(msg[msg_idx]) orelse continue;
            space_needed += @sizeOf(T);
        }
    }

    if (space_needed == 0) {
        // Nothing to format - short-circuit to simpler API.  (This is mostly to
        // avoid the zero-length-buffer edge case below).
        w4.trace(msg);
        return;
    }

    var buf: [space_needed]u8 = undefined;
    var buf_slice: []u8 = buf[0..];
    comptime var arg_idx: usize = 0;
    comptime var msg_idx: usize = 0;
    inline while (msg_idx < msg.len) : (msg_idx += 1) {
        if (msg[msg_idx] != '%') {
            continue;
        }
        msg_idx += 1;
        switch (msg[msg_idx]) {
            '%' => {},
            'd', 'c', 'x', 'f' => |c| {
                const T = charType(c) orelse unreachable;
                buf_slice = pack(buf_slice, @as(T, args[arg_idx]));
                arg_idx += 1;
            },
            's' => {
                const s: [*:0]const u8 = switch (@typeInfo(@TypeOf(args[arg_idx]))) {
                    .Pointer => args[arg_idx],
                    .Array => &args[arg_idx],
                    else => unreachable,
                };
                const T = charType('s') orelse unreachable;
                buf_slice = pack(buf_slice, @as(T, @ptrToInt(s)));
                arg_idx += 1;
            },
            else => unreachable,
        }
    }
    w4.tracef(msg.ptr, &buf);
}
```

I'm  happy to contribute my wrapper if wanted, though I'm not sure whether such thicker wrappers belong in the wasm4 repo or not.

**Comment by joshgoebel** [comment]
Nice!!!  I wonder if using slices is more expensive (space wise) than just keeping a pointer into the buffer of where we are currently at...

Are we going to be able to have both a public `tracef` (Zig) as well as the `extern` (WASM-4 API) one?  Calling `w4.tracef` is of course going to run our function... we still need a way for that to dispatch to WASM-4 API.

>  though I'm not sure whether such thicker wrappers belong in the wasm4 repo or not.

If that's the native code that's needed to interface with the API on the WASM-4 side then I think it's _necessary_.

**Comment by sporksmith** [comment]
> I wonder if using slices is more expensive (space wise) than just keeping a pointer into the buffer of where we are currently at...

I don't think it'll make a substantial difference; A slice is just a pointer + length.

> If that's the native code that's needed to interface with the API on the WASM-4 side then I think it's *necessary*.

There could be other ways of doing it with different tradeoffs. I guess as long as we expose the "raw" API as well, people could still roll their own. zig is pretty good about removing functions that aren't actually called.

**Comment by sporksmith** [comment]
I poked around a little bit to see how much cart space this saves.

Starting with a fresh zig project (`w4 create --zig w4test`), and compiling with size optimization enabled (`zig build -Drelease-small=true`). I added a very thin wrapper around `trace` that uses the zig standard library to do formatting, and the above `tracef` wrapper, and then logged a single line that formats an integer, a hex integer, and a float

In this case it saves quite a bit - around 4.5 KB.

| trace call  | Total cart size |
| ------------- | ------------- |
| None  | 493 bytes  |
| `std.fmt.bufPrintZ` + `wasm4.trace`| 5322 bytes  |
| `tracef` wrapper  | 867 bytes  |

OTOH it may not save as much if the zig formatting code is already being pulled in for other purposes, such as to format strings that are rendered in game.

**Comment by sporksmith** [comment]
I tried seeing if we could just use the C declaration that's used in the generated C skeleton, but it looks like the zig compiler doesn't support C varargs for wasm yet. https://github.com/ziglang/zig/issues/1481#issuecomment-1002159188

**Comment by joshgoebel** [comment]
OMG, it'd sure be nice if the compiler just did that all for us... I had simply imagined we weren't there yet, but if that's on the roadmap that's nice to know and might change how much effort we put into it on our end?

**Comment by sporksmith** [comment]
Ah hah, it actually does work! I just needed to cast the integer parameter to an `i32`. Doing it this way will require more explicit casting at the call sites, and won't be type checked, but maybe ok for a bare minimum wrapper to the runtime.

Afaict it does require creating a C header file and importing it, which is slightly ugly :/

**Comment by sporksmith** [comment]
Ok, I thought if zig understands varargs in C declarations, maybe it secretly understands them in `extern` declarations too... and it does! So it looks like all we need is

```
pub extern fn tracef(x: [*:0]const u8, ...) void;
```

in wasm4.zig. This still has the explicit casting and lack of type checking caveats, but at least is an easy minimal way to access the function.

One slight bummer is that if we declare the `extern tracef` this way, I'm not sure there's a straightforward way to write a type checked wrapper for it as above. I think  folks who want to do that could just edit/replace the import, though.

I'll go ahead and put together a PR

**Comment by joshgoebel** [comment]
```
pub extern fn tracef(x: [*:0]const u8, ...) void;
```

Wait, really that just works?  It does all the pointer math for you?

**Comment by sporksmith** [comment]
Yup. No type checking or coercion though, so if you pass the wrong types you'll just get garbage. e.g. `tracef("%d", @as(f64, 3.14))` will happily compile, but won't print the right thing.

**Comment by lambdadog** [comment]
For anyone coming to this issue from the `wasm4.zig` source who's not immediately worried about the extra executable size from pulling in zig's formatting code, I wrote up this code to implement logging using WASM-4's `trace`. It has to go in "main.zig" (at least the `log_level` and `log` function), since Zig reads several settings from your root file.

```zig
const std = @import("std");

// ...

// ReleaseSmall's default log_level is .err
pub const log_level = .info;

const Wasm4Tracer = struct {
    buffer: [256]u8 = .{0} ** 256,
    end: usize = 0,

    const Writer = std.io.Writer(*@This(), Error, write);

    const Error = error{
        OutOfMemory,
    };

    extern fn traceUtf8(str: [*]const u8, len: usize) void;
    fn send(self: *@This()) void {
        traceUtf8(&self.buffer, self.end);
        self.end = 0;
    }

    fn writer(self: *@This()) Writer {
        return .{ .context = self };
    }

    fn write(self: *@This(), bytes: []const u8) Error!usize {
        if (bytes.len + self.end > 256)
            return Error.OutOfMemory;

        for (bytes[0..bytes.len]) |b, i| self.buffer[i + self.end] = b;
        self.end += bytes.len;

        return bytes.len;
    }
};

pub fn log(
    comptime message_level: std.log.Level,
    comptime scope: @Type(.EnumLiteral),
    comptime format: []const u8,
    args: anytype,
) void {
    const level_txt = comptime message_level.asText();
    const prefix2 = if (scope == .default) ": " else "(" ++ @tagName(scope) ++ "): ";

    var tracer: Wasm4Tracer = .{};
    tracer.writer().print(level_txt ++ prefix2 ++ format ++ "\n", args) catch return;
    tracer.send();
}
```

Things to keep in mind: Due to comptime analysis, Zig only includes formatters for the types (and formatters) of things you specifically print during the course of your code. This means that if you print a float with {d}, it includes the decimal printing code for floats, and if you print an int with {d} it includes the decimal printing codes for ints, etc.

Additionally, you can use scopes and log_level (I recommend reading [log.zig](https://github.com/ziglang/zig/blob/master/lib/std/log.zig)) to essentially completely remove logging calls from your code at compile-time. By setting a public `scope_levels` variable in your root file, you can assign a scope to a specific log level (say, "debug"), and if your `log_level` doesn't include said log level, zig will use conditional compilation to not include the code in your final cart.

Of course, `tracef` will always be smaller because it's just directly calling an external function which adds essentially 0 size to your cart, so if you're running out of cart space it probably makes sense to use it, but Zig's logging facilities are much nicer so I personally prefer to use them if possible.
