### ISSUE TITLE
Add blue screen of death for WASM crashes

### ISSUE THREAD

**Issue by joshgoebel** [aduros/wasm4#245]
When there is a known common WASM crash, we should indicate it visibly.  Memory out of bounds errors seem to be quite common in my development so far.  If there were other common ones we could handle those as well.  I'm happy to work on this if we could agree on wording and visual style.

Mockup

![Screen Shot 2021-12-26 at 4 05 40 PM](https://user-images.githubusercontent.com/6473/147420100-6d8793e0-4e71-4eef-a7df-25f559c631e3.png)
:

**Comment by joshgoebel** [comment]
Or even a bomb or some "crash" icon on a colored background would be better than it just appearing to freeze as it does now...

**Comment by aduros** [comment]
Sounds useful, and I think you nailed the aesthetic.

Would this also work for wasm `unreachable` statements?

**Comment by desttinghim** [comment]
It should be possible, I believe an exception is thrown to JavaScript when unreachable is executed, so we'd just need to catch it and run the blue screen script.

**Comment by joshgoebel** [comment]
Can someone find me some C of Zig code or even assembly script with unreadable that is reached?

**Comment by joshgoebel** [comment]
![Screen Shot 2021-12-27 at 8 35 10 AM](https://user-images.githubusercontent.com/6473/147476821-f4894a2e-5a1c-4618-a59f-9a1ff10f143e.png)

Any other major cases we should handle?  If the case itsn't known it will just default (on the web) to showing `[name] [message]` from the error object, which is better than nothing I think.

**Comment by aduros** [comment]
You can call `__builtin_trap()` in clang to emit an `unreachable` instruction.
