### ISSUE TITLE
Implement audio on native builds

### ISSUE THREAD

**Issue by OliveIsAWord** [aduros/wasm4#248]
With recent pull requests, WASM-4 has become a much more capable target for music and sound effects, which makes it all the more important that audio also be present on native builds rather than restricted to web builds. This is an essential feature that is currently missing from Windows/Mac/Linux executables.

**Comment by meshula** [comment]
My LabSound project (https://github.com/LabSound/LabSound) is a complete implementation of WebAudio for native, and has a PortAudio backend. LabSound works on rpi3-4, which is not a potato, but is a raspberrypi :) I had a look at the WASM4 audio code, and there is a one-to-one compatibility with LabSound.

I'm happy to whip up the C interfaces you need, if anyone wants to have a go.

**Comment by joshgoebel** [comment]
So what audio backends are you using for each platform to actually output the audio?  Or I suppose one should perhaps argue we shouldn't even care about that?

**Comment by aduros** [comment]
This is mostly done, but opened #312 as a follow up task.
