### ISSUE TITLE
Poor performance in Firefox

### ISSUE THREAD

**Issue by adamjc** [aduros/wasm4#260]
Issue: Running the games through Firefox doesn't give a smooth framerate

Replicate: Open up any of the games in Firefox

**Comment by tjpalmer** [comment]
I haven't measured, but I use Firefox and haven't noticed issues.

**Comment by christopher-kleine** [comment]
I'm using firefox as my daily driver. And on my PC I never had an issue. On the Pi however, I do. That is because firefox on the Pi doesn't have hardware acceleration.
WASM-4 uses WebGL. If you don't have drivers or firefox can't work with them, the performance will be poor, yes.

**Comment by locriacyber** [comment]
Even the template application (press x to blink) consumes a lot of computing power.

**Comment by JerwuQu** [comment]
The audio engine seems to suffer a bit as well in Firefox (compared to a Chromium browser).

The noise channel sounds a bit different, and if you do `tone`s very rapidly (which is used for arpeggios) it messes up completely. This may be related to #308, I don't know.

**Comment by JerwuQu** [comment]
Is this still an issue? I would expect this was fixed in the frame-timing rewrite years back.

**Comment by adamjc** [comment]
Running Firefox 125.0.1. Played a few demos on the showcase page, seems to be running very smoothly now :) (and I'm impressed by some of these games!)
