### ISSUE TITLE
png2src for single bit images

### ISSUE THREAD

**Issue by XeroOl** [aduros/wasm4#267]
png2src works great if I have a 4-color image that I want to use, but currently a 2-color image still needs to be written by hand. I think it would be nice to be able to use the same png workflow regardless of the type of sprite to create.

**Comment by christopher-kleine** [comment]
Looking at the source of png2src (https://github.com/aduros/wasm4/blob/main/cli/lib/png2src.js) this should already be handled.

**Comment by XeroOl** [comment]
Ahh, I didn't see it as an option to png2src, so I thought it wasn't present. I didn't realize it inferred the flags based on the image.
