### ISSUE TITLE
Example pixel functions fail to subtract 1 from draw color

### ISSUE THREAD

**Issue by sporksmith** [aduros/wasm4#270]
The `DRAW_COLOR`s are numbered 1-4, but are represented in the `FRAMEBUFFER` with 2 bits as 0-3. The example pixel functions fail to take this into account. e.g. from https://wasm4.org/docs/guides/basic-drawing/?code-lang=assemblyscript#direct-framebuffer-access :

```
// Use the first DRAW_COLOR as the pixel color
const color = u8(load<u16>(w4.DRAW_COLORS) & 0b11);
// Write to the framebuffer
store<u8>(w4.FRAMEBUFFER + idx, (color << shift) | (load<u8>(w4.FRAMEBUFFER + idx) & ~mask));
```

The documentation is also a bit light on this in general, though this behavior is implied by 
 e.g. "[Each draw color can be a value between 1 and 4 representing a palette color, or 0 to signify transparency.](https://wasm4.org/docs/reference/memory#draw_colors)".

Test program that demonstrates the mapping (in zig):

```
export fn update() void {
    w4.tracef("before: %x", @as(u32, w4.FRAMEBUFFER[0]));

    var color: u8 = 0;
    while (color <= 4) : (color += 1) {
        w4.DRAW_COLORS.* = color;
        w4.rect(0, 0, 1, 1);
        w4.tracef("after rect with DRAW_COLORS=%d, FRAMEBUFFER[0]=%d", @as(u32, w4.DRAW_COLORS.*), @as(u32, w4.FRAMEBUFFER[0]));
    }
}
```

Produces output:

```
before: 0
after rect with DRAW_COLORS=0, FRAMEBUFFER[0]=0
after rect with DRAW_COLORS=1, FRAMEBUFFER[0]=0
after rect with DRAW_COLORS=2, FRAMEBUFFER[0]=1
after rect with DRAW_COLORS=3, FRAMEBUFFER[0]=2
after rect with DRAW_COLORS=4, FRAMEBUFFER[0]=3
```

**Comment by joshgoebel** [comment]
This is correct.  The frame buffer (per pixels) is 2-bit it can only hold 0 1 2 3.

The 1-4 only exists at the API level.  I assume it's to make it "Easier" for some people, but it is confusing.

**Comment by sporksmith** [comment]
Which `this` are you referring to? I'm not suggesting a bug in `w4` itself, just in the example `pixel` functions on the website.

**Comment by joshgoebel** [comment]
Oh, sorry, spoke too soon.  Yeah the pixel function looks entirely broken. :-)  You can't mask `0b11` the DRAW_COLOR or you'll just mask out 4 entirely...  Think it would be `-1` then mask?

**Comment by sporksmith** [comment]
In hindsight I see how my original description could have been read differently. I made a pass to clarify that the bug is about the `pixel` demo functions (and to a lesser extent the documentation of this behavior)
