### ISSUE TITLE
Update will be called at most 1 time per animation frame, despite time elapsed possibly being > 1/60s

### ISSUE THREAD

**Issue by DenialAdams** [aduros/wasm4#278]
https://github.com/aduros/wasm4/blob/2c8c0127eb03dd690dae20a2187a0124b1358318/runtimes/web/src/index.js#L478

For instance, if a browser is only giving us animation frames at a rate 30fps, then games will update at half of the rate that they should.

If the linked code was a loop instead of an if statement, then we could potentially call update multiple times in a single animation frame. Games would feel worse than they would at 60fps, but at least they would update at full speed. I feel like this would be an improvement.

Potential downside: "spiral of death" if the game consistently takes longer than 1/60th of a second to update and we keep trying to catch up, resulting in a growing number of simulations per animation frame. But the behavior will suck either way if your game really takes that long to update!

I'm writing this issue just as a result of looking at the source, so I haven't tested how this would work in practice - could be missing something :)

**Comment by joshgoebel** [comment]
> only giving us animation frames at a rate 30fps

Is that still true for some displays?

**Comment by DenialAdams** [comment]
> > only giving us animation frames at a rate 30fps
> 
> Is that still true for some displays?

At least iOS will throttle the animation frame to 30fps when running on battery

https://bugs.webkit.org/show_bug.cgi?id=168837

**Comment by aduros** [comment]
This should be implemented as of 2.4.0! Please re-open if it's still an issue.
