### ISSUE TITLE
[docs bug] After following site Instructions in wasm4/site/README.md, still can't play carts on localhost

### ISSUE THREAD

**Issue by DenialAdams** [aduros/wasm4#279]
This makes it harder to debug some issues. I don't see a clear error message in the console. carts are present at build/carts

![image](https://user-images.githubusercontent.com/2072405/148291334-1cdc9e8c-ad64-439e-bf24-664af87cac2b.png)

url was http://localhost:3000/play/racer

**Comment by christopher-kleine** [comment]
Did you build the runtime too?
You need to go to `runtimes/web` and follow their README.md too.
