### ISSUE TITLE
C: `start` function fails to run if `time` is used 

### ISSUE THREAD

**Issue by ZapAnton** [aduros/wasm4#282]
wasm4 version: 
- 2.0.0

When the `srand(time(NULL))` line is used in the `start` function, the function does not seem to run. Because of it, the browser version of the program freezes and the native version does not output any trace.

Code to reproduce:
```c
#include <time.h>
#include <stdlib.h>
#include "wasm4.h"

void start () {
    trace("Hello start!");
    srand(time(NULL));
    trace("Hello start 2!");
}
```
The first and the second `trace` will not work without commenting the `srand` line

**Comment by DenialAdams** [comment]
WASM-4 doesn't provide any functionality to get the system time, so I suspect that's why time(NULL) isn't working. Perhaps diagnostics could be improved here though (I haven't used C + wasm4 personally)

**Comment by ZapAnton** [comment]
Indeed, removing the `time(NULL)` solves the problem with `start` running.

**Comment by ZapAnton** [comment]
It is strange though, when I tried using any printing functions that are not provided by wasm4 (`printf`, `puts`) ,I got an error message at runtime:
```text
WASM error: missing imported function.
```
This is not the case with `time` it seems

**Comment by ZapAnton** [comment]
Is there a way to get time-related functions to work with C?

**Comment by DenialAdams** [comment]
> Is there a way to get time-related functions to work with C?

Time and an official RNG are both intentionally omitted to make the games deterministic. I don't have anything to link (it would be nice if this was documented somewhere) but it's come up on the discord several times and @aduros explained the above

**Comment by joshgoebel** [comment]
@ZapAnton Please feel free to add your voice to #72

**Comment by ZapAnton** [comment]
Thank you for linking the relevant issue.
I will close this one since it is a duplicate.
Do you think a separate issue regarding better error messages for such cases could be open?

**Comment by aduros** [comment]
Thanks, I opened #272 (PR at #276) for adding better error reporting for startup failures.
