### ISSUE TITLE
Reset Game on Mobile

### ISSUE THREAD

**Issue by XeroOl** [aduros/wasm4#285]
On a computer, players can press R to reset the console, but there is no way to restart the game on a mobile web browser.

**Comment by sporksmith** [comment]
+1 this would be nice. I ended up implementing a "soft reset" inside my game, but it took some work and is easy to get wrong. I guess the user can always refresh the page, but that's a lot less ergonomic, especially when playing full screen on mobile.

**Comment by joshgoebel** [comment]
TIC-80 has a `reset()` API for this where a cartridge can reset itself (and let the engine clean up, reboot it, etc).

**Comment by aduros** [comment]
I would love to have a button that brings up a pause menu with options like:

- Reboot
- Save State
- Load State
- Save Screenshot?
- etc.

**Comment by aduros** [comment]
The latest version has a button that brings up that pause menu!
