### ISSUE TITLE
C: `run-native` does not work with an empty `update` function

### ISSUE THREAD

**Issue by ZapAnton** [aduros/wasm4#292]
affected wasm4 versions:
- 2.0.0
- `main` branch on the 086dfa8 commit

Steps to reproduce:

- w4 new --c hello && cd hello
- edit `src/main.c`:
```c
#include "wasm4.h"
void update () {
 }
```
- make
- w4 run-native build/cart.wasm

Expected behavior:
Cart window with the default background color opens and stays

Actual behavior:
Cart window with the black background opens and closes in 1 second

Whats strange is that the same behavior is shown when the update function contains code:
```c
#include "wasm4.h"
void update () {
    rect(10, 10, 32, 32);
}
``` 
But, if the update function contains a call to `text` it works as intended:
```c
#include "wasm4.h"

void update () {
    text("Hello from C!", 20, 20);
    rect(10, 10, 32, 32);
}
``` 

Os: Arch Linux
`uname -a`:  Linux 5.15.13-arch1-1 #1 SMP PREEMPT Wed, 05 Jan 2022 16:20:59 +0000 x86_64 GNU/Linux

**Comment by aduros** [comment]
Thanks for reporting this! It seems to only happen if the cart doesn't use memory at all.
