### ISSUE TITLE
Bug on the site

### ISSUE THREAD

**Issue by MrNektom** [aduros/wasm4#310]
![Screenshot_2022-01-12-23-33-36-931_com brave browser](https://user-images.githubusercontent.com/40566268/149218065-99b06abd-ac92-4f36-91c4-4799039f594b.jpg)

**Comment by christopher-kleine** [comment]
Ditch brave. Problem solved.
And I mean it. Garuda Linux comes with a fork of Firefox. And it does something similar. You can't execute any games on it. 3rd rate browsers often have problems displaying bleeding edge websites.

**Comment by MrNektom** [comment]
The problem with displaying the site on a smartphone, the frame with the video goes beyond the main content, this is a layout problem, not a browser one.

**Comment by aduros** [comment]
I think I slightly broke the landing page layout on mobile when the video was added. It's definitely our bug.

**Comment by MrNektom** [comment]
Yes, it's because of the video frame, its width is not limited by the screen width.
