### ISSUE TITLE
`run` command fails due to MIME mismatch

### ISSUE THREAD

**Issue by ZapAnton** [aduros/wasm4#313]
wasm4 version:
- 2.2.0, `main` branch at 9db63e0

Using `w4 run` results in a blank web page being open with two errors in the console:

- The resource from “http://localhost:4444/wasm4.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)
- The resource from “http://localhost:4444/wasm4.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). 

wasm4 at the 086dfa8 commit runs normally

Browser:
Firefox 96.0

**Comment by christopher-kleine** [comment]
How did you install WASM-4? Using git and clone? It that case you might need to build the runtime first.
In that case, check `runtimes/web` for informations.

**Comment by ZapAnton** [comment]
I have built wasm4 using git in the following order: `devtools/web` -> `runtimes/native` -> `runtimes/web` -> `cli`

**Comment by ZapAnton** [comment]
Seems like a mistake on my part - the first run of `npm run build` failed and I did not notice.
Closing, sorry for the noise

**Comment by christopher-kleine** [comment]
It's better to ask twice and get solve the issue than never ask and abandon the project entirely. So: Thanks!
