### ISSUE TITLE
Permission to add WASM-4 to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by fpscan** [aduros/wasm4#314]
Hi there, we would like to seek your permission to include WASM-4 as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

**Comment by aduros** [comment]
Please do! Thanks for asking :smile:

**Comment by LibretroAdmin** [comment]
It took a while but it's finally here -
https://store.steampowered.com/app/1876450/RetroArch__WASM4/

You can talk to gadsby in case you'd like any changes made to the descriptions and whatnot.
