### ISSUE TITLE
Mouse y position is inverted on native runtime

### ISSUE THREAD

**Issue by pfgithub** [aduros/wasm4#315]
I'm not sure if this is glfw or minifb but it should be pretty easy to fix

On: macos x86_64 version 12.1

![image](https://user-images.githubusercontent.com/6010774/149404325-22789043-aaea-4ac2-953e-a8e37ac38130.png)

This can be tested easily with the [minesweeper cartridge](https://github.com/aduros/wasm4/blob/main/site/static/carts/minesweeper.wasm)

**Comment by thedavesims** [comment]
This was an upstream issue with MiniFb: https://github.com/emoon/minifb/issues/66

I'll double check.

**Comment by JerwuQu** [comment]
Does this issue still exist on the current `main`?

**Comment by pfgithub** [comment]
It's fixed on latest main
