### ISSUE TITLE
Add panning to `tone`

### ISSUE THREAD

**Issue by JerwuQu** [aduros/wasm4#320]
Two new flags `TONE_PAN_LEFT` and `TONE_PAN_RIGHT` to pan a sound completely left or completely right, similar to on a Gameboy.

**Comment by aduros** [comment]
I like that the proposed implementation is elegant and a non-breaking change, but I'm reluctant to add new functionality at the moment. I feel like the use-cases for stereo sound in 2D games are kind of limited, and especially in 2D retro games, so not sure if it's worth the additional API surface.

**Comment by joshgoebel** [comment]
In my quick googling it seems stereo was pretty common on Gameboy at least (if you plugged in headphones):

> All the Pokemon games (except for the original red and blue) support stereo sound but it needs to be enabled in the options menu. It makes for a pretty fun headphone experience. The soundtracks are great in stereo, and in battles, the sounds come from either side of the screen.

 Stereo seems an easy (even at the time) way to add extra depth of experience to 2D games of the time - so it's not a surprise people took advantage of that. Not sure about other retro systems.  I played so much on TV and doubtful I would have noticed the stereo.

> I feel like the use-cases for stereo sound in 2D games are kind of limited,

I mean if we just simply don't want more features (or API surface) that's your call, but I think I'd have to disagree with "use cases are limited" being the justification.  Just my 0.02.

**Comment by JerwuQu** [comment]
I don't think it's limited in usage at all when considering music, but it can also make for cooler sound effects. I see it as a small addition that will have big impact.

As @joshgoebel said, it was pretty common and a lot of games used it.
Here's a couple of examples: [Final Fantasy Adventure: Endless Battle](https://www.youtube.com/watch?v=Or0qv44SVmo), [Super Mario Land's Overworld Theme](https://www.youtube.com/watch?v=Gb33Qnbw520).

**Comment by sporksmith** [comment]
Another example I have fond memories of on gameboy, Final Fantasy Legend: https://youtu.be/BoeKZq6vNfQ
