### ISSUE TITLE
Go target.json example needs global base setting

### ISSUE THREAD

**Issue by jimmycartrette** [aduros/wasm4#33]
Starting playing off the go hello world, noticed my KEYS and Framebuffer were getting overwritten with variables in memory. Looks like this link from the rust linker options
        "--global-base=6560"
 in target.json in the go hello world cleared things up

**Comment by jimmycartrette** [comment]
#34 
Created my first ever PR

**Comment by jimmycartrette** [comment]
That didn't fix it, but I'm not sure how to. I haven't used a debugger but it seems like doing things that generate variables in the heap seems to put them in lower memory first, overwriting controls and videobuffer. For example this code below which just assigns a pointer to a new variable causes the keys to be pressed and a moving dot around the framebuffer

var messy *[]byte
...
	var createvar []byte = fullland
	messy = &createvar

[screenshot of corruption](https://imgur.com/wAOFkGM)

Without that, the program is completely normal. Or if I use a text() is also starts to corrupt pretty much immediately.

**Comment by aduros** [comment]
Hi, thanks for reporting this!

Yeah, from what I could tell `--global-base` doesn't seem to do anything (https://github.com/rust-lang/rust/issues/46645#issuecomment-423912553)

The workaround was setting the stack size to offset the memory to the correct place... but I think it needs to be larger than 6560, to actually leave room for a stack.

Can you try changing `-zstack-size` in target.json from 6560 to 7584? (or higher) That will leave 1024+ bytes for the actual stack.

**Comment by jimmycartrette** [comment]
I tried even 30336, verified that's the first stack address but the problem doesn't change. I tried to debug but it's a bit over my head. I made a repo with the first commit with no problems, and a second commit with three lines (global pointer, int and value assignment to global pointer) that causes the issue. No issues
https://github.com/jimmycartrette/LakeShooter/commit/ca9676d95c6eb8f65bec4334503cc1b87c2ac2a5

And has corruption issues:
https://github.com/jimmycartrette/LakeShooter/commit/206101cff2f7322a4a6ba488e3178ea19ace6647

Interesting though, just introducing a single global pointer variable doubles the size of my compiled code.

**Comment by aduros** [comment]
Thanks, it looks like any heap allocation causes memory corruption. Here's a minimal repro case:

```go
package main

var test []byte;

//go:export update
func update () {
    test = make([]byte, 666);
}
```

It will quickly crash due to out of memory (which is another unrelated issue... why isn't the GC running?) but more relevantly the allocator seems to be writing bookkeeping data to the low memory region reserved by WASM-4, which is causing the corruption.

**Comment by jimmycartrette** [comment]
There is no GC for WASM from TinyGo, and it doesn't seem to have any native memory management. I suspect that's enough to kill the idea of using Go for a 64K game of any real complexity.

**Comment by aduros** [comment]
Hmm, GC should be supported by TinyGo on all platforms. Do you have a link with more info about GC not being supported on TinyGo+wasm?

**Comment by jimmycartrette** [comment]
Nevermind, it does seem to use TinyGo's conservative GC. However, it doesn't seem to be working

**Comment by aduros** [comment]
I think we fixed heap allocation in Go, could you try again on the latest version? You'll also need to copy the latest [target.json](https://github.com/aduros/wasm4/blob/main/cli/assets/templates/go/target.json) to replace the copy in your project directory.
