### ISSUE TITLE
Nim wants wasi `proc_exit` for functions that can raise exceptions

### ISSUE THREAD

**Issue by tjpalmer** [aduros/wasm4#339]
Much of the Nim standard library can raise exceptions, and @Yardanico explains:
> right now if you use code that can make a nim exception, the compilation will fail because nim calls quit on unhandled exceptions and it gets compiled in the wasm file so a WASI import gets emitted

We also have one submission that has forked wasm4 because of this:
> If you want to play from the cartridge, you'll need to install our fork of wasm4. Since we used Nim, we found that we needed to add a function to the WASM-4 runtime (wasi_snapshot_preview1.proc_exit), to use any of the standard library.
> Otherwise, we'd get "Uncaught (in promise) TypeError: import object field 'wasi_snapshot_preview1' is not an Object" errors while running the game. This is the only modification we did to the WASM-4 runtime.

One solution is to see if there's a way to override the call to `proc_exit` in Nim, but I doubt they'll make core changes to Nim in this regard just to support wasm4 (but I could be wrong), so I suspect it would have to be an override option already available in Nim, which @Yardanico might already have employed if it were easy.

Meanwhile, [the forked wasm4 from the submission mentioned earlier adds a net 7 lines of code](https://github.com/aduros/wasm4/compare/main...willGuimont:main) to wasm4 to support a function call that other languages also seem maybe likely to emit in the future.

Interestingly, [my own usage of Nim std in wasm4](https://github.com/tjpalmer/child/blob/500cff8f73d0027c23cafb9f86aaa3b036d53352/src/cart.nim) hasn't hit this issue yet.

**Comment by tjpalmer** [comment]
While a separate issue, [the `png2src` change](https://github.com/aduros/wasm4/commit/e29c5b894beb98b2170e4509e717dcf7e98743bd) in the forked wasm4 [also looks correct](https://nim-lang.org/docs/tut1.html#advanced-types-arrays).

**Comment by aduros** [comment]
I think this is fixed by adding the new compiler flag to Nim, but feel free to re-open if I missed something.

We also picked up the `png2src` change in a previous commit :smiley:
