### ISSUE TITLE
Ovals across screen edge wrap or something

### ISSUE THREAD

**Issue by tjpalmer** [aduros/wasm4#347]
I don't have a screenshot handy, but this at least starts tracking the issue.

**Comment by Tinchetsu** [comment]
I was going to report this as well. Attaching gif from a game I'm making for wasm4 gamejam.

The bullets are ovals, when they go offscreen, they wrap.
![game](https://user-images.githubusercontent.com/10901731/150585112-4b41327f-115d-4b78-aa5b-ba61e103a900.gif)

**Comment by JerwuQu** [comment]
I'll start tackling this one now
