### ISSUE TITLE
png2src should sort the palette

### ISSUE THREAD

**Issue by aduros** [aduros/wasm4#358]
Currently png2src sorts the palette based on the order that it encounters colors in the image. This is a problem because modifying the image can result in the palette being shuffled.

Let's sort the palette by the image colors ARGB values, with a special case for indexed pngs where we sort using the index of the color in the png palette.

**Comment by pfgithub** [comment]
In my own tool, I'm sorting by HSL Lightness which sorts from dark to light

**Comment by aduros** [comment]
Oh, that's an even better idea :smiley:
