### ISSUE TITLE
Docs: Saving Data questions

### ISSUE THREAD

**Issue by jaller94** [aduros/wasm4#367]
I'd find it helpful if the guide answered the following questions about saving data:

* How where is the data being saved?
  * e.g. localStorage in web
  * What about standalone executables?
* Are different games getting different save disks? How are they being told apart?
  * e.g. If multiple games are published on one website, (how) are they not overwriting each other's saves?
* If there are different saves per game, is it possible to upgrade a game?
  * I've started a [Pokemon-like RPG](https://jaller94.gitlab.io/wasm4-monster-collector) and wonder if I will be able to update the game and still continue old saves. (Obviously, the game would need to handle versioning of save formats itself.)

**Comment by JerwuQu** [comment]
> Are different games getting different save disks? How are they being told apart?

This question depends on #357, so we can solve that, then handle all your points in one go!
