### ISSUE TITLE
Update website post-game jam

### ISSUE THREAD

**Issue by aduros** [aduros/wasm4#375]
- Bring in all the new carts from the game jam (with screenshots and metadata)
- Feature jam winners somehow
- Add info to Community section
- Remove announcement bar
- Probably keep the landing page video because it's a good general intro

**Comment by JerwuQu** [comment]
Might be possible to tie in some things from #298 too

I think the Markdown part especially might be useful for games that require more explanation.
Possibly a `<slug>.md` in the same directory that gets rendered through JS?
Linking to the itch.io page might suffice for now though, and would be good anyways.

**Comment by gouchi** [comment]
Also what is the licence for the carts ?

As we would like to [add them to the content downloader](https://github.com/libretro/libretro-content/pull/32).

Thank you.

**Comment by JerwuQu** [comment]
> As we would like to https://github.com/libretro/libretro-content/pull/32.

On this note, perhaps it would be worth it for the site to store a hash for each cart so that versions can be compared. Could be useful for both downloading/updating content and netplay later on.

**Comment by aduros** [comment]
@gouchi The carts were recently licensed under [CC BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/). It's ok to redistribute them as long as the authors are credited and they're not used commercially.

For the libretro content downloader, can we ensure that the author metadata is included somehow?

cc @RobLoach

**Comment by gouchi** [comment]
They are **[referenced in the database](https://github.com/libretro/libretro-database/blob/master/dat/WASM-4.dat)** so when the user scan the file they can get the information.

But we can't have it directly in the content downloader.

@RobLoach Do you concur ?

**Comment by RobLoach** [comment]
I think it would be best if we also copy in the `.md` files in the libretro-content .zip files too.
