### ISSUE TITLE
Add some sort of random seed source

### ISSUE THREAD

**Issue by gnarz** [aduros/wasm4#401]
As we can not rely on the operating system for this, it would be neat to have a few bytes (like, 4 or 8), that are different on each invocation of w4. The intent is to use them as a random seed source, so that games whose level layout depends on random numbers don't always look the same. Anything would be fine, like a timestamp or something, as long as it changes with each invocation. Alternatively there could be a function to do that.

**Comment by aduros** [comment]
#365 adds a timestamp which might be useful here.

Alternatively you can use the gamepad input to seed the RNG (such as frames elapsed on your game's title screen before getting to the actual gameplay)

**Comment by tjpalmer** [comment]
> Alternatively you can use the gamepad input to seed the RNG (such as frames elapsed on your game's title screen before getting to the actual gameplay)

I'm mentioning the title screen trick in the video I'm making, by the way.
