### ISSUE TITLE
I can't make a html bundle

### ISSUE THREAD

**Issue by Andre-LA** [aduros/wasm4#433]
Hello,

After bundling to html file, the game doesn't works and it triggers a runtime error on console.

Source code: https://github.com/Andre-LA/totally-not-sumo

Build and bundle: [totally-not-sumo-compiled.zip](https://github.com/aduros/wasm4/files/8547346/totally-not-sumo-compiled.zip)

Bundling command: 
```sh
$ ~/Downloads/programas/w4 bundle --html totally-not-sumo.html --title "Totally not Sumo" --icon-url ico.png totally-not-sumo.wasm
```

Console:
```
Uncaught (in promise) TypeError: URL constructor: null is not a valid URL.
    pt file:///home/dreunix/origami-sword/totally-not-sumo/build/totally-not-sumo.html:71
    init file:///home/dreunix/origami-sword/totally-not-sumo/build/totally-not-sumo.html:77
```

Seems that the problems happens on the `pt` function, which seems that is called with `pt("netplay")`.

For instance I also tried bundling to linux using `--linux`, and this one generated a working linux executable.

w4 version: `2.4.0`.

I already made successful html bundle of this game on w4 `2.2.0` on the past.

**Comment by aduros** [comment]
Thanks for reporting this, it might be a regression in 2.4 when loading bundled carts from `file://`
