### ISSUE TITLE
on itch.io html bundle from linux doesnt render for linux/android

### ISSUE THREAD

**Issue by skrshe** [aduros/wasm4#449]
With linux wasm4 version `2.4.0` the html bundle works when run directly, but when uploaded to itch.io the game screen appears black and doesnt change.
On android the same happens but the buttons are visible and pressing the white button above `a/b` brings up menu, but menu doesn't cycle with `arrows`.

**Comment by aduros** [comment]
The fix should now be in the latest release (2.5.0), please re-open if this is still happening.
