### ISSUE TITLE
Gamepad not working in Firefox in Linux

### ISSUE THREAD

**Issue by metiulekm** [aduros/wasm4#470]
Hi,

I couldn't get my gamepad to work on Firefox. It works correctly in <https://gamepad-tester.com>, and it also works correctly when I try running a WASM-4 game in Chrome.

Details:
- Arch Linux with Plasma,
- WASM-4 2.5.0 (AUR package: `wasm4-bin 2.5.0-1`), but the same thing happens on <https://wasm4.org/play>,
- Firefox 102.0.1 (Arch package: `firefox 102.0.1-1`). Sadly I couldn't get WASM-4 to work at all in the Firefox troubleshooting mode, but I did disable extensions and nothing changed,
- gamepad is 8BitDo SN30 Pro+ detected by Gamepad Tester as `Xbox Wireless Controller 045e-02e0-8BitDo SN30 Pro+`,
- the only things I see in the console when running locally are
  ```
  Lit is in dev mode. Not recommended for production! See https://lit.dev/msg/dev-mode for more information. [reactive-element.js:38:20](http://localhost:4444/node_modules/@lit/reactive-element/development/reactive-element.js)
  Multiple versions of Lit loaded. Loading multiple versions is not recommended. See https://lit.dev/msg/multiple-versions for more information. [reactive-element.js:38:20](http://localhost:4444/devtools/web/node_modules/@lit/reactive-element/development/reactive-element.js)
  Warning: Cart is larger than 65536 bytes. Ensure the release build of your cart is small enough to be bundled. [runtime.ts:267:20](http://localhost:4444/src/runtime.ts)
  ```
  (the last one due to testing using `snake-rust`).

Due to my total ineptitude when it comes to webdev I haven't really investigated this too much. One thing that I did manage to find is that `navigator.getGamepads()` works differently across those two browsers: in Chrome it returns `[null, null, null, null]` (as shown by DevTools) before touching the gamepad and `[Gamepad, null, null, null]` afterwards, but in Firefox there are no `null`s: before touching the gamepad it returns `[]` and after touching `[Gamepad]`. This does feel relevant but I don't know.

**Comment by aduros** [comment]
Hi, thanks for the detailed report!

I'm guessing Firefox doesn't have a mapping of that controller to the "standard" gamepad layout. Can you try removing standard mapping check at https://github.com/aduros/wasm4/blob/dadea9f7ba23f4937a0bc0e317c21bec01177034/runtimes/web/src/ui/app.ts#L377 ? Assuming that works, some of the buttons may be incorrectly mapped though.

**Comment by metiulekm** [comment]
Ok, I did so, and then I followed `/tmp/wasm4/runtimes/web/README.md` up to `npm start`. Then what happened then is that when I did something with the gamepad (both dpad and the analog stick did the same thing), the game stopped, and in the console I saw
```
Uncaught TypeError: buttons[12] is undefined
    pollPhysicalGamepads app.ts:386
    update app.ts:421
    loop app.ts:471
    setTimeout handler*loop app.ts:480
    setTimeout handler*loop app.ts:480
    setTimeout handler*loop app.ts:480
    (bunch more repetitions)
    setTimeout handler*loop app.ts:480
```
For the record, `navigator.getGamepads()[0].buttons` is an array of length 10. Also, `navigator.getGamepads()[0].mapping` is an empty string.

I did see you discussing this [here](https://github.com/aduros/wasm4/pull/104#discussion_r712518612), so it's probably not fixable easily?

**Comment by aduros** [comment]
I would try reporting this to Mozilla, especially since Chrome supports the standard mapping.

Alternatively I would accept a PR that tries to detect this controller and do the mapping in JS. That wouldn't be ideal though, and might break in the future.

**Comment by aduros** [comment]
> I might add this when I find some time if you agree.

That would be great!
