### ISSUE TITLE
Netplay not working on bundled deployment, despite the same cart working fine on localhost during development

### ISSUE THREAD

**Issue by DenialAdams** [aduros/wasm4#484]
Reproduction URL: https://www.brick.codes/spunky.html

steps:
1) Browse to URL
2) Share netplay link
3) Connect using netplay link in incognito window
4) Observe that player2 (on wasm4.org) can see player1, but player1 (on brick.codes) can't see player2

(as a side note, I recommend using chrome when testing, firefox seems to have performance issues)

**Comment by DenialAdams** [comment]
It works fine on itch.io
https://brickcodes.itch.io/spunky

so something is wrong with my domain somehow, but I'd still like to learn how to fix it

**Comment by aduros** [comment]
The exact same bundled file works on itch but not your domain? That's really weird...

Have you tested other carts?

**Comment by DenialAdams** [comment]
> The exact same bundled file works on itch but not your domain? That's really weird...
> 
> Have you tested other carts?

yes! I haven't tested other carts, but I'll try to do so

**Comment by DenialAdams** [comment]
I can no longer reproduce the issue with latest `w4` and `rolandc` and the game
