### ISSUE TITLE
tone parameters are in wrong order for import stubs

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [aduros/wasm4#59]
The [Rust](https://github.com/aduros/wasm4/blob/main/cli/assets/templates/rust/src/wasm4.rs#L109) stub in the default uses the following declaration for `tone`:
```rs
pub fn tone (frequency: u32, volume: u32, duration: u32, flags: u32) {
    unsafe { extern_tone(frequency, volume, duration, flags) }
}
extern {
    #[link_name = "tone"]
    fn extern_tone (frequency: u32, volume: u32, duration: u32, flags: u32);
}
```

However, the APU in the javascript source code uses the following parameter order:
```js
tone (frequency, duration, volume, flags)
```

The same seems to be the case for [AssemblyScript](https://github.com/aduros/wasm4/blob/main/cli/assets/templates/assemblyscript/src/wasm4.ts#L85), [Go](https://github.com/aduros/wasm4/blob/main/cli/assets/templates/go/src/wasm4.go#L87) and [C](https://github.com/aduros/wasm4/blob/main/cli/assets/templates/c/src/wasm4.h#L89).

This doesn't cause any problems in practice, but causes editor hints to be wrong.

**Comment by aduros** [comment]
Thank you so much for flagging this!
