### ISSUE TITLE
`png2src` not rendering variable types in Rust output

### ISSUE THREAD

**Issue by nathanjent** [aduros/wasm4#60]
An issue has come up in wasm4@1.0.3 not present in 1.0.2. The types for non-array constants are not being rendered when running `w4 png2src`. I believe this only affects the Rust variant since the other supported languages don't require this type signature on constant variables.

### Expected

 This is the output from wasm4@1.0.2

    const spritesheetWidth: u32 = 16;
    const spritesheetHeight: u32 = 32;
    const spritesheetFlags: u32 = 1; // BLIT_2BPP
    const spritesheet: [u8; 128] = [
        // ...
    ];

### Actual

This is the output from wasm4@1.0.3. I do appreciate the variable naming update to match Rust style. :heart: 

    const SPRITESHEET_WIDTH = 16;
    const SPRITESHEET_HEIGHT = 32;
    const SPRITESHEET_FLAGS = 1; // BLIT_2BPP
    const SPRITESHEET: [u8; 128] = [
        // ...
    ];

**Comment by aduros** [comment]
Thank you for reporting this!
