### ISSUE TITLE
Suggestion: display runtime version number on menu

### ISSUE THREAD

**Issue by MrRafael-dev** [aduros/wasm4#641]
Games exported with different `w4` versions will inevitably include different runtime versions aswell.
By displaying a version number on bottom of the menu, it would be possible to check how updated/outdated a given version is.

Although not really a big deal, sometimes it happens that a game available on multiple platforms (e.g. **[the WASM-4 site](https://wasm4.org/play)** and **[itch.io](https://itch.io/games/tag-wasm4)**) may have a few differences between them (sound/performance), even when both games are essentially the same, with no "old versions".

Of course, it's up to the authors if they decide to re-export their games with an updated `w4` or not, but when that's not the case, then players can look at the version and try looking for a newer one somewhere else.

**Comment by aduros** [comment]
For what it's worth, HTML bundles contain a line like this containing the version, eg:

```html
<meta name="generator" content="WASM-4 2.5.1">
```
