### ISSUE TITLE
[Go] Suggestion: change trace function to take array of bytes instead of string in golang

### ISSUE THREAD

**Issue by tomsiemek** [aduros/wasm4#66]
I wanted to debug some stuff and print some integers to the console. I wrote some integer printing code.  

```go
func printInt(r int) {
	var bytes [6]byte
	bytesIndex := 5
	byteLen := 0
	const MAXX = 1000_000
	for i := 10; i < MAXX; i *= 10 {
		rem := r % i
		bytes[bytesIndex] = digitToByte(rem * 10 / i)
		r -= rem
		bytesIndex--
		byteLen++
		if r < 1 || bytesIndex < 0 {
			break
		}
	}
	trace(string(bytes[:]), byteLen)
}
```

But after few prints the colors in game started changing. The problem were hidden memory allocations during string operations. The problem is strings in golang allocate on the heap on creation. It seems that this heap allocation doesn't care where it allocates memory and my color pallete got overwritten by string data! I think it would be better if the trace function in golang was like c++ version so it takes array of bytes so we avoid allocating memory with string type. Like this:

```go
func trace (str []byte, byteLength int);
```

**Comment by aduros** [comment]
We definitely need to fix the bug with heap allocation in Go (#33).

Instead of adding a new method, I think you can manually change the `wasm4.go` in your project to use the C string version:

```go
//go:export trace
func trace (str *byte);
```

(The byte array must end with a zero byte to terminate the string)

**Comment by tomsiemek** [comment]
Thanks that helps. But I found something else. Every time I used array (even with length ascribed on compile time my screen will bet messed up a little (random artifacts). 
![random_pixels](https://user-images.githubusercontent.com/14972669/132157436-a1f4245d-bc68-42d6-8b66-fa9ee169b2ef.png)
It turns out that every time you use array you do heap allocation. I just tested it with simple code like this in update function:
```go
func update() {
	frameCount++
	var bb [4]byte
	bb[0] = 'a'
	bb[1] = 'a'
	bb[2] = 'a'
	bb[3] = '\000'
//....
```
If u remove the array code everything is fine. So it's hard to use arrays in go with wasm4.

**Comment by aduros** [comment]
@tomsiemek Could you try your original printInt() again on the latest version? You'll also need to copy the latest [target.json](https://github.com/aduros/wasm4/blob/main/cli/assets/templates/go/target.json) to replace the copy in your project directory.

**Comment by tomsiemek** [comment]
@aduros If I change target.json the thing doesn't start at all. I get error like this in console:
![image](https://user-images.githubusercontent.com/14972669/132747571-f92b6f2e-d53e-42ad-b38e-2df99dc6e4da.png)

**Comment by aduros** [comment]
Thanks, hmm. Could you please share a zip of your project?

**Comment by tomsiemek** [comment]
Sure, you can also see in example project https://github.com/aduros/wasm4/tree/main/cli/assets/templates/go , if you add few lines which allocate on the heap to the update function like that:
```go
...
var someArr [4]byte
someArr[0] = 0
someArr[1] = 1
someArr[2] = 2
someArr[3] = 3
...
```
you will see artifacts on the screen (using the new target json).
[wasm4-go.zip](https://github.com/aduros/wasm4/files/7140958/wasm4-go.zip)

**Comment by aduros** [comment]
Thanks, that helped! I updated [target.json](https://github.com/aduros/wasm4/blob/main/cli/assets/templates/go/target.json) again, can you apply it to your project? The game seems to fully work for me now.

**Comment by tomsiemek** [comment]
It also works for me. There are no glitches on the screen so I assume it doesn't allocate where it shouldn't anymore. Thanks!

**Comment by aduros** [comment]
Great, thanks!
