### ISSUE TITLE
w4 bundle corrupted

### ISSUE THREAD

**Issue by eXponenta** [aduros/wasm4#67]
For large carts that less that 64kb, bundle emit invalid HTML.

I have a cart size 16kb and 44kb of HTML, but browser was crash with `Unexpected identifier`

Cart:
https://github.com/eXponenta/wasm4-game/tree/main/build

Page:
https://exponenta.github.io/wasm4-game/build/my-super-game.html

This reproduced on 1.0.3 version and on 1.0.4 version of wasm4.

Lang is AsemblyScript.

**Comment by aduros** [comment]
@FaberVitale is working on improving `w4 bundle` (#58), I bet this will be fixed once those changes land.

**Comment by FaberVitale** [comment]
The following issue happens on 1.03 and 1.0.4 with `site/static/carts/pong.wasm` too.

I've got a fix ready that will be included in the `bundle` refactor #58

### Cartriges that do not work with bundle cmd

- https://github.com/eXponenta/wasm4-game/blob/403f7aa79352422775f560839b2cccf5f6c39df7/build/cart.wasm
- https://github.com/aduros/wasm4/blob/fd49edc5a2858c36d6a770c2bc829669fa2110b0/site/static/carts/pong.wasm

**Comment by eXponenta** [comment]
Looks like that this is bug in node regExp on very large replacer, because a generated source was a `....z85 data <script src=wasm4></script> ...z85 data`, regexp replace regions partially.

I think we can replace reqexp onto indexOf + subst and concatenation
