### ISSUE TITLE
[native runtime] BSOD on pointer buffer overruns and invalid memory access

### ISSUE THREAD

**Issue by JerwuQu** [aduros/wasm4#709]
See this comment for previous discussion https://github.com/aduros/wasm4/pull/599#pullrequestreview-1203505916.

Functions that take pointers in the C runtime should check that they are valid rather than silently trim any out-of-bounds access. If such cases are detected, BSOD so the user can fix the issue.

**Comment by JerwuQu** [comment]
Fixed!

**Comment by aduros** [comment]
Fixed by #751
