### ISSUE TITLE
Nim: error with randomize: WASM error: missing imported function ('wasi_snapshot_preview1.fd_prestat_get')

### ISSUE THREAD

**Issue by ov7a** [aduros/wasm4#734]
Using sample code:
```nim
import cart/wasm4
import std/random

# Call NimMain so that global Nim code in modules will be called, 
# preventing unexpected errors
proc NimMain {.importc.}

proc start {.exportWasm.} = 
  NimMain()
  randomize()
```

I get:
```
WASM error: missing imported function ('wasi_snapshot_preview1.fd_prestat_get')
```

I'm using nim 2.0.6 and w4 2.7.0 on Linux.
For nim 1.6.4, I get the same error.

Is there a way to fix this?

**Comment by ov7a** [comment]
Note that in the save environment, this sample works fine:
```nim
import cart/wasm4
import strutils

# Call NimMain so that global Nim code in modules will be called, 
# preventing unexpected errors
proc NimMain {.importc.}

proc start {.exportWasm.} = 
  NimMain()
  trace(intToStr(10))
```  
so the problem is related to the `random`.

**Comment by tjpalmer** [comment]
Yeah, I expect little to no wasi support from wasm4, so you might just have to avoid such functions that expect more from the system. And unless it's changed, there's also no clock in wasm4 nor other sources of entropy. Some clever folks have used mouse motion from the user or delays to game start or other things to seed their own pseudo random number generator.

**Comment by tjpalmer** [comment]
Or I guess if Nim's rand works for you, then yeah, just use tricks based on user input to give it a seed.

**Comment by ov7a** [comment]
Thanks! Frame counter trick with `randomize(frame_counter)` works.

I guess there is no need to keep this issue open
