### ISSUE TITLE
Libretro buildbot failures

### ISSUE THREAD

**Issue by LibretroAdmin** [aduros/wasm4#768]
Hi there,

I think this was the last time all the Libretro targets still built succesfully -

https://git.libretro.com/libretro/wasm4/-/pipelines/302211

Something happened after merging this PR that caused a bunch of failures since -

https://git.libretro.com/libretro/wasm4/-/pipelines/302363

**Comment by yamt** [comment]
is it using an ancient cmake (<3.13) for some reasons?
cf. https://cmake.org/cmake/help/latest/command/target_link_directories.html

**Comment by yamt** [comment]
> is it using an ancient cmake (<3.13) for some reasons? cf. https://cmake.org/cmake/help/latest/command/target_link_directories.html

https://github.com/aduros/wasm4/commit/0795bd9936d640f6d46a6137a80f790e7d3ca1cf#commitcomment-147685154

**Comment by yamt** [comment]
a proposed fix: https://github.com/aduros/wasm4/pull/769
