### ISSUE TITLE
Let's release a 2.7.1 version!

### ISSUE THREAD

**Issue by matm** [aduros/wasm4#785]
Two recent merges #723 (June 7) and #783 (December 12) have been done after the [2.7.0 release](https://github.com/aduros/wasm4/releases/tag/v2.7.0) (April 22).

By releasing a 2.7.1 that includes at least these 2 patches, it would make the `hello-world` tutorials for the Go and Zig programming languages work again, which would be very nice for newcomers to this project!

Thanks!

**Comment by matm** [comment]
Reading the tutorials and failing at build time is a very frustrating experience IMO. It should just work out of the box.

**Comment by aduros** [comment]
Absolutely, I'll do a release later today. Thanks for the poke 🙂
