### ISSUE TITLE
Add example of direct framebuffer manipulation to the docs

### ISSUE THREAD

**Issue by aduros** [aduros/wasm4#96]
The `FRAMEBUFFER` memory region can be directly written to for drawing, but that's not very well explained in the docs. Let's add a section to the graphics documentation showing how to write a single pixel for example.

**Comment by FaberVitale** [comment]
You could export `drawPointUnclipped` without the first argument or provide inside the templates a simple `drawPixel` function.

**Comment by eXponenta** [comment]
> You could export `drawPointUnclipped` without the first argument or provide inside the templates a simple `drawPixel` function.

drawPoint how and other JS calls is slowly than write framebuffer direct,  because this is JS interropt.
Implement a draw commands in WASM side is good point.

**Comment by SirBoneHead** [comment]
> Implement a draw commands in WASM side is good point.

This is a good idea. It could allow each language to use and optimize the draw functions in their own way.

**Comment by aduros** [comment]
Yeah :smiley: The plan is not to add more drawing functions but to show how to write to the framebuffer directly.

**Comment by aduros** [comment]
I added some examples, but I wasn't sure of the best Rust implementation.

Calling our resident Rust expert @FaberVitale :eyes:
