### ISSUE TITLE
[suggestion] Native Gamepad support  

### ISSUE THREAD

**Issue by eXponenta** [aduros/wasm4#99]
Will be good to intorudce a Gamepad support in game and menu.
This allow to use this platform like Steam Big Screen in AndroidTV, Tablet or Real Consoles with WebGL/Canvas support (like Xbox, PS5).

For runtime this will be easy, and because site have grid, looks like that Gamepad navigation can be implemented and on it.

**Comment by aduros** [comment]
Sounds good! Let's start with the runtime implementation using [Gamepad API](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API). PRs would be very welcome here.

After that's implemented we can follow up with adding an in-game pause menu (which will be good to have even without a gamepad), and adding gamepad navigation to the wasm4.org website.
